---
- name: Set hostname and domain
  eos_system:
    hostname: "{{ inventory_hostname }}-ansible"
    domain_name: "{{ domain_name }}"
    domain_search: "{{ domain_search }}"

- name: Configure name servers
  eos_system:
    name_servers: "{{ name_servers }}"
