---
- name: Remove system configs
  eos_system:
    state: absent
    domain_name:
    domain_search:

- name: Remove name servers
  eos_system:
    state: absent
    name_servers:
      - 192.168.1.1
      - 3.3.3.3
      - 8.8.8.8