- name: Remove system configs
  junos_system:
    state: absent
    domain_name:
    domain_search:

- name: Remove name servers
  junos_system:
    state: absent
    name_servers:
      - 192.168.1.1
      - 3.3.3.3
      - 8.8.8.8

- name: Remove Banner
  junos_banner:
    banner:  login
    state: absent