- debug:
    var: hostvars['ansible_net_hostname']
- name: Generate HTML report
  template:
    src: report.j2
    dest: "{{playbook_dir}}/reports/index.html"
  run_once: true

# - name: copy CSS over
#   become: yes
#   copy:
#     src: "css"
#     dest: "{{ file_path }}"
#     directory_mode: true

# - name: copy CSS over
#   become: yes
#   copy:
#     src: "webpage_logo.png"
#     dest: "{{ file_path }}"
#     directory_mode: true

# - name: display link to inventory report
#   debug:
#     msg: "Please go to http://{{hostvars[web_host].ansible_host}}:{{web_port}}"
